### ISSUE TITLE
 !  Couldn't find a $VERSION in prerequisite Bio::Perl

### ISSUE THREAD

**Issue by smacmil** [nanoporetech/barcoding#1]
I'm having trouble compiling even though I have the latest version of BioPerl installed (1.006924) I keep getting the error
 !  Couldn't find a $VERSION in prerequisite Bio::Perl
I have set the PERL5LIB path to point to this latest version uner my .profile

Please see below:
perl -MBio::Perl -le 'print Bio::Perl->VERSION;'
1.006924
 perldoc -l Bio::Perl
/usr/local/share/perl/5.18.2/Bio/Perl.pm
perl -V

> ........
> %ENV:
>     PERL5LIB="/usr/local/share/perl/5.18.2/Bio/:\/usr/local/share/perl/site_perl/5.18.2/Bio:\/usr/local/share/perl/site_perl"
>   @INC:
>     /usr/local/share/perl/5.18.2/Bio/
>     \/usr/local/share/perl/site_perl/5.18.2/Bio
>     \/usr/local/share/perl/site_perl
>     /etc/perl
>     /usr/local/lib/perl/5.18.2
>     /usr/local/share/perl/5.18.2
>     /usr/lib/perl5
>     /usr/share/perl5
>     /usr/lib/perl/5.18
>     /usr/share/perl/5.18
>     /usr/local/lib/site_perl

How do I point to the version of Bio::Perl

**Comment by rmp** [comment]
Hi. At what point is that error being thrown? make / perl Build.PL or somewhere else?

It looks likely from your @INC that there's more than one installation of perl. What does "which perl" say?

Depending how your BioPerl installation was performed (e.g. with "cpan" commandline tool), there should be no reason to modify PERL5LIB beyond the defaults.

Also PERL5LIB generally should not need to contain escaped slashes ( \/ ), or subdirectories which are part of module distributions (i.e. the lines referencing Bio).
